# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('project_id', models.AutoField(db_column='pId', primary_key=True, serialize=False)),
                ('project_title', models.CharField(db_column='Title', max_length=120)),
                ('project_start', models.DateField(db_column='Start_Date')),
                ('project_end', models.DateField(db_column='End_Date', default=datetime.date.today)),
                ('project_file', models.CharField(db_column='FileName', default='proj_0.jpg', max_length=50)),
                ('project_url', models.CharField(db_column='Link', default='https://github.com/5hirish', max_length=250)),
                ('project_tech', models.CharField(db_column='Tech', max_length=250)),
                ('project_description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
    ]
