# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170613_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='project_current',
            field=models.BooleanField(db_column='Current', default=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='project_file',
            field=models.CharField(db_column='FileName', default='proj_0.png', max_length=50),
        ),
    ]
